id = "patchwork"
name = "Patchwork"
description = "Patchwork language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["David Herman <david.herman@gmail.com>"]
repository = "https://github.com/dherman/patchwork"

[grammars.patchwork]
repository = "file:///Users/dherman/Code/patchwork"
rev = "main"
path = "tree-sitter"

[language_servers.patchwork]
languages = ["Patchwork"]
command = "patchwork-lsp"
